name: Generate pacman animation

on:
  schedule:
    - cron: "*/10 * * * *" # jalan tiap 10 menit
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          theme: "github-dark"

      - name: Prepare dist
        run: |
          mkdir -p dist
          cp pacman-contribution-graph*.svg dist/ || echo "No pacman SVG found!"

      - name: Push pacman-contribution-graph.svg to the pacman-output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: pacman-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
