name: Generate pacman animation

on:
  schedule: 
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          theme: dark   # ⬅️ Tambahin ini biar background dark

      - name: Debug list files
        run: ls -lah

      - name: prepare dist
        run: |
          mkdir -p dist
          mv pacman-contribution-graph*.svg dist/

      - name: push pacman-contribution-graph.svg to the pacman-output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: pacman-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
